apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: llm-project

build:
  artifacts:
    - image: llm-api
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl: {}

portForward:
  - resourceType: deployment
    resourceName: llm-api
    port: 8000
    localPort: 8000
